// Generated by Glitch!
// Wed Oct 19 21:10:21 2022

void loop(void)
{
 digitalWrite(LED_BUILTIN, HIGH);
 delay(1000);
 digitalWrite(LED_BUILTIN, LOW);
 delay(1000);
}

void setup(void)
{
 pinMode(LED_BUILTIN, OUTPUT);
}
