// Generated by Glitch!
// Fri Aug 5 22:47:29 2022

void loop(void)
{
	digitalWrite(LED_BUILTIN, HIGH);
	delay(1000);
	digitalWrite(LED_BUILTIN, LOW);
	delay(1000);
}

void setup(void)
{
	pinMode(LED_BUILTIN, OUTPUT);
}
