// Generated by Glitch!
// Sun Jul 17 20:28:04 2022

void loop(void)
{
	digitalWrite(LED_BUILTIN, HIGH);
	delay(1000);
	digitalWrite(LED_BUILTIN, LOW);
	delay(1000);
}

void setup(void)
{
	pinMode(LED_BUILTIN, OUTPUT);
}
