// Generated by Glitch!
// Sat Jul 2 23:20:17 2022

void loop(void)
{
	int sensorValue = analogRead(A0);
	Serial.println(int sensorValue = analogRead(A0););
	delay(1);
}

void setup(void)
{
	Serial.begin(9600);
}
