// Generated by Glitch!
// Fri Aug 5 11:29:12 2022

int thisByte = 33;

void loop(void)
{
	Serial.write(thisByte);
	Serial.print(", dec: ");
	Serial.print(thisByte);
	Serial.print(", hex: ");
	Serial.print(thisByte, HEX);
	Serial.print(", oct: ");
	Serial.print(thisByte, OCT);
	Serial.print(", bin: ");
	Serial.println(thisByte, BIN);
	if(thisByte == 126)
	{
		while(true)
	{
		continue;
	}
	}
	thisByte = ((thisByte) + (1));
}

void setup(void)
{
	Serial.begin(9600);
	while(!Serial)
	{
	}
	Serial.println("ASCII Table ~ Character Map");
}
