// Generated by Glitch!
// Sun Jul 17 20:52:22 2022

const static long C0 = 0x736f6d6570736575L;

int m_c_rounds_index = 1;

const static long C1 = 0x646f72616e646f6dL;

int m_d_rounds_index = 1;

const static long C2 = 0x6c7967656e657261L;

const static long C3 = 0x7465646279746573L;

void loop(void)
{
}

void setup(void)
{
}
