// Generated by Glitch!
// Sun Jul 17 21:50:26 2022

const static long C0 = 0x736f6d6570736575L;

const static long C1 = 0x646f72616e646f6dL;

const static long C2 = 0x6c7967656e657261L;

const static long C3 = 0x7465646279746573L;

int m_c_rounds_index = 1;

int m_d_rounds_index = 1;

long m_v0 = 0L;

long m_v1 = 0L;

long m_v2 = 0L;

long m_v3 = 0L;

const static int KEY_LENGTH = 16;

/*
** Variables are presented before other obj
** ects regardless of order.
*/

long byteArrayToLong()
{
}

long rotl()
{
}

void round()
{
}

void loop(void)
{
}

void setup(void)
{
}
