// Generated by Glitch!
// Sat Jul 9 12:30:18 2022

int pushButton = 2;

void loop(void)
{
	int buttonState = digitalRead(pushButton);
	Serial.println(buttonState);
	delay(1);
}

void setup(void)
{
	Serial.begin(9600);
	pinMode(pushButton, INPUT);
}
