// Generated by Glitch!
// Tue Jul 19 16:11:34 2022

const static long  = 0x736f6d6570736575L;

long byteArrayToLong()
{
}

const static long  = 0x646f72616e646f6dL;

long rotl()
{
}

void round()
{
}

const static long  = 0x6c7967656e657261L;

const static long  = 0x7465646279746573L;

int  = 1;

int  = 1;

long  = 0L;

long  = 0L;

long  = 0L;

long  = 0L;

const static int  = 16;

void loop(void)
{
}

void setup(void)
{
}
