// Generated by Glitch!
// Wed Jul 20 14:31:32 2022

void loop(void)
{
	int sensorValue = analogRead(A0);
	float voltage = ((sensorValue) * (((5.0) / (1023.0))));
	Serial.println(voltage);
}

void setup(void)
{
	Serial.begin(9600);
}
