// Generated by Glitch!
// Mon Apr 21 19:59:28 2025

const int ledPin  = LED_BUILTIN;

int ledState  = LOW;

unsigned long previousMillis  = 0;

const long interval  = 1000;

void loop(void)
{
 unsigned long currentMillis  = millis();
 if(currentMillis - previousMillis >= interval)
  {
   previousMillis = currentMillis;
   if(ledState == LOW)
   {
    ledState = HIGH;
   }
   else
   {
    ledState = LOW;
   }
   digitalWrite(ledPin, ledState);
  }
}

void setup(void)
{
 pinMode(ledPin, OUTPUT);
}
