// Generated by Glitch!
// Wed Oct 19 21:09:29 2022

const int ledPin  = LED_BUILTIN;

int ledState  = LOW;

unsigned long previousMillis  = 0;

const long interval  = 1000;

void loop(void)
{
 unsigned long currentMillis  = millis();
 if(currentMillis - previousMillis >= interval)
 {
  previousMillis = currentMillis;
  if(ledState == LOW)
  {
   ledState = HIGH;
  }
  else
  {
   ledState = LOW;
  }
  digitalWrite(ledPin, ledState);
 }
}

void setup(void)
{
 pinMode(ledPin, OUTPUT);
}
