// Generated by Glitch!
// Mon Aug 1 22:52:06 2022

const int buttonPin = 2;

const int ledPin = 13;

int buttonState = 0;

void loop(void)
{
	buttonState = digitalRead(buttonPin);
	if(buttonState == HIGH)
	{
		digitalWrite(ledPin, HIGH);
	}
	else
	{
		digitalWrite(ledPin, LOW);
	}
}

void setup(void)
{
	pinMode(ledPin, OUTPUT);
	pinMode(buttonPin, INPUT);
}
