// Generated by Glitch!
// Fri Jul 8 22:50:53 2022

int led = 9;

int brightness = 0;

int fadeAmount = 5;

void loop(void)
{
	analogWrite(led, brightness);
	delay(30);
}

void setup(void)
{
	pinMode(led, OUTPUT);
}
