// Generated by Glitch!
// Wed Jul 13 22:06:40 2022

int brightness = 0;

int fadeAmount = 5;

int led = 9;

void loop(void)
{
	analogWrite(led, brightness);
	brightness = ((brightness) + (fadeAmount));
	if(brightness <=0 || brightness >= 255)
	{
	}

	delay(30);
}

void setup(void)
{
	pinMode(led, OUTPUT);
}
