FORMS          += UI/Arduino/glitch-object-advanced-io-arduino.ui \
                  UI/Arduino/glitch-object-analog-io-arduino.ui \
                  UI/Arduino/glitch-object-arithmetic-operator-arduino.ui \
                  UI/Arduino/glitch-object-bits-and-bytes-arduino.ui \
                  UI/Arduino/glitch-object-bitwise-operator-arduino.ui \
                  UI/Arduino/glitch-object-block-comment-arduino.ui \
                  UI/Arduino/glitch-object-characters-arduino.ui \
                  UI/Arduino/glitch-object-compound-operator-arduino.ui \
                  UI/Arduino/glitch-object-constant-arduino.ui \
                  UI/Arduino/glitch-object-digital-io-arduino.ui \
                  UI/Arduino/glitch-object-flow-control-arduino.ui \
                  UI/Arduino/glitch-object-function-arduino.ui \
                  UI/Arduino/glitch-object-logical-operator-arduino.ui \
                  UI/Arduino/glitch-object-loop-arduino.ui \
                  UI/Arduino/glitch-object-mathematics-arduino.ui \
                  UI/Arduino/glitch-object-random-arduino.ui \
                  UI/Arduino/glitch-object-serial-arduino.ui \
                  UI/Arduino/glitch-object-setup-arduino.ui \
                  UI/Arduino/glitch-object-time-arduino.ui \
                  UI/Arduino/glitch-object-trigonometry-arduino.ui \
                  UI/Arduino/glitch-object-utilities-arduino.ui \
                  UI/Arduino/glitch-object-variable-arduino.ui
HEADERS	       += Source/Arduino/glitch-object-advanced-io-arduino.h \
                  Source/Arduino/glitch-object-analog-io-arduino.h \
                  Source/Arduino/glitch-object-arithmetic-operator-arduino.h \
                  Source/Arduino/glitch-object-bits-and-bytes-arduino.h \
                  Source/Arduino/glitch-object-bitwise-operator-arduino.h \
                  Source/Arduino/glitch-object-block-comment-arduino.h \
                  Source/Arduino/glitch-object-characters-arduino.h \
                  Source/Arduino/glitch-object-compound-operator-arduino.h \
                  Source/Arduino/glitch-object-constant-arduino.h \
                  Source/Arduino/glitch-object-digital-io-arduino.h \
                  Source/Arduino/glitch-object-flow-control-arduino.h \
                  Source/Arduino/glitch-object-function-arduino.h \
                  Source/Arduino/glitch-object-logical-operator-arduino.h \
                  Source/Arduino/glitch-object-loop-arduino.h \
                  Source/Arduino/glitch-object-mathematics-arduino.h \
                  Source/Arduino/glitch-object-random-arduino.h \
                  Source/Arduino/glitch-object-setup-arduino.h \
                  Source/Arduino/glitch-object-serial-arduino.h \
                  Source/Arduino/glitch-object-time-arduino.h \
                  Source/Arduino/glitch-object-trigonometry-arduino.h \
                  Source/Arduino/glitch-object-variable-arduino.h \
                  Source/Arduino/glitch-structures-arduino.h \
                  Source/Arduino/glitch-object-utilities-arduino.h \
		  Source/Arduino/glitch-view-arduino.h
SOURCES	       += Source/Arduino/glitch-object-advanced-io-arduino.cc \
                  Source/Arduino/glitch-object-analog-io-arduino.cc \
                  Source/Arduino/glitch-object-arithmetic-operator-arduino.cc \
                  Source/Arduino/glitch-object-bits-and-bytes-arduino.cc \
                  Source/Arduino/glitch-object-bitwise-operator-arduino.cc \
                  Source/Arduino/glitch-object-block-comment-arduino.cc \
                  Source/Arduino/glitch-object-characters-arduino.cc \
                  Source/Arduino/glitch-object-compound-operator-arduino.cc \
                  Source/Arduino/glitch-object-constant-arduino.cc \
                  Source/Arduino/glitch-object-digital-io-arduino.cc \
                  Source/Arduino/glitch-object-flow-control-arduino.cc \
                  Source/Arduino/glitch-object-function-arduino.cc \
                  Source/Arduino/glitch-object-logical-operator-arduino.cc \
                  Source/Arduino/glitch-object-loop-arduino.cc \
                  Source/Arduino/glitch-object-mathematics-arduino.cc \
                  Source/Arduino/glitch-object-random-arduino.cc \
                  Source/Arduino/glitch-object-serial-arduino.cc \
                  Source/Arduino/glitch-object-setup-arduino.cc \
                  Source/Arduino/glitch-object-time-arduino.cc \
                  Source/Arduino/glitch-object-trigonometry-arduino.cc \
                  Source/Arduino/glitch-object-utilities-arduino.cc \
                  Source/Arduino/glitch-object-variable-arduino.cc \
                  Source/Arduino/glitch-structures-arduino.cc \
		  Source/Arduino/glitch-view-arduino.cc
