.TH Glitch 1 "May 27, 2019"
.SH NAME
Glitch
.SH SYNOPSIS
.B Glitch [options]
.SH DESCRIPTION
.B Glitch
is a graphical interface for generating Arduino-compliant source from graphical diagrams.
.SH OPTIONS
.TP
.BI --help
Display available command-line options.
.TP
.BI --new-arduino-diagram " name"
Create the specified Arduino diagram. Multiple instances are supported.
.TP
.BI --open-arduino-diagram " name"
Open the specified Arduino diagram. An absolute file name must be provided. Multiple instances are supported.
.TP
.BI --version
Display version information and exit.
.SH NOTES
.SH AUTHOR(S)
.B Alexis Megas
