.TH Glitch 1 "April 24, 2024"
.SH NAME
Glitch
.SH SYNOPSIS
.B Glitch [options]
.SH DESCRIPTION
.B Glitch
is a graphical interface capable of generating Arduino-compliant source from
graphical diagrams.
.SH OPTIONS
.TP
.BI --full-screen
Display Glitch in a full-screen window.
.TP
.BI --generate-source
Generate the source of the diagrams specified by --open-arduino-diagrams.
.TP
.BI --help
Display available command-line options.
.TP
.BI --new-arduino-diagram " name"
Create the specified Arduino diagram. Multiple instances are supported.
.TP
.BI --open-arduino-diagrams " file-name(s)"
Open the specified Arduino diagram(s). Multiple instances are supported.
.TP
.BI --show-serial-port-window
Display the Serial Port Window.
.TP
.BI --show-tools
Display Tools dialog(s). Requires a diagram.
.TP
.BI --version
Display version information and exit.
.SH NOTES
.SH AUTHOR(S)
.B Alexis Megas
