.TH Glitch 1 "January 29, 2024"
.SH NAME
Glitch
.SH SYNOPSIS
.B Glitch [options]
.SH DESCRIPTION
.B Glitch
is a graphical interface capable of generating Arduino-compliant source from
graphical diagrams.
.SH OPTIONS
.TP
.BI --full-screen
Display Glitch in a full-screen window.
.TP
.BI --help
Display available command-line options.
.TP
.BI --new-arduino-diagram " name"
Create the specified Arduino diagram. Multiple instances are supported.
.TP
.BI --open-arduino-diagram " absolute-file-name"
Open the specified Arduino diagram. An absolute file name must be provided.
Multiple instances are supported.
.TP
.BI --show-serial-port-window
Display the Serial Port Window.
.TP
.BI --show-tools
Display Tools dialog(s). Requires a diagram.
.TP
.BI --version
Display version information and exit.
.SH NOTES
.SH AUTHOR(S)
.B Alexis Megas
