.TH GlowBot 1 "February 28, 2017"
.SH NAME
GlowBot
.SH SYNOPSIS
.B GlowBot [options]
.SH DESCRIPTION
.B GlowBot
is a graphical interface for generating Arduino-compliant source from graphical diagrams.
.SH OPTIONS
.TP
.BI --new-arduino-diagram " name"
Launch GlowBot and create the specified Arduino diagram. Multiple instances are supported.
.TP
.BI --version
Display version information and exit.
.SH NOTES
.SH AUTHOR(S)
.B Alexis Megas
